spring:
  application:
    name: im-pos-service-commod
  jmx:
    default-domain: im-pos-service-commod
logging:
  level:
    root: INFO
    tk.mybatis: TRACE
mybatis:
    type-aliases-package: com.inmarket.pos.model
    mapper-locations: classpath*:mapper/*.xml
impos:
  location: /Users/elnino/Workspace/runtime/
mapper:
    mappers:
      - com.inmarket.pos.data.util.MSMapper
    not-empty: false
    identity: ORACLE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/
  instance:
      preferIpAddress: true
logging:
  config: classpath:logback-spring.xml
  file: ./log/${spring.application.name}