spring:
  application:
    name: im-pos-service-admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
      turbine:
        url:  im-pos-service-admin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/
    instance:
      preferIpAddress: true
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
turbine:
  appConfig: im-pos-service-commod,im-pos-service-entrance
  cluster-name-expression: new String('default')
  combine-host-port: true
info:
  version: '180718.SNAPSHOT'



