spring:
  application:
    name: im-pos-service-entrance
  jmx:
    default-domain: im-pos-service-entrance
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: develop
ribbon:
  ReadTimeout: 20000
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 20000
    threadpool:  
      default:  
        coreSize: 500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/
  instance:
   preferIpAddress: true
