server:
  port: 8180                    # 指定该Eureka实例的端口
  context-path: 
spring:
  jmx:
    default-domain: im-pos-service-registeration
  profiles:
    active: develop
---
spring:
  profiles: develop
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.context-path}/eureka/

---
spring:
  profiles: product
eureka:
  instance:
    hostname: registeration
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registeration:${server.port}${server.context-path}/eureka/
