spring:
  application:
    name: im-pos-service-common    # 项目名称尽量用小写
  jmx:
    default-domain: im-pos-service-commod
impos:
  location: /opt/impos/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/    # 指定注册中心的地址
  instance:
      preferIpAddress: true
      statusPageUrlPath: ${server.context-path}/info
      healthCheckUrlPath: ${server.context-path}/health
