spring:
  application:
    name: im-pos-service-management    # 项目名称尽量用小写
  jmx:
    default-domain: im-pos-service-management
logging:
  level:
    root: INFO 
    tk.mybatis: INFO
mybatis:
    type-aliases-package: com.inmarket.pos.model
    mapper-locations: classpath*:mapper/*.xml
impos:
    location: /opt/impos/
mapper:
    mappers:
      - com.inmarket.pos.data.util.MSMapper
    not-empty: false
    identity: ORACLE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8180/eureka/    # 指定注册中心的地址
  instance:
      preferIpAddress: true
